repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/ambv/black
  rev: 23.3.0
  hooks:
  - id: black
    # Since the pre-commit runs on a file by file basis rather than a whole project,
    # The excludes in pyproject.toml are ignored
    exclude: migrations
    language_version: python3
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
    language_version: python3
