repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    # Since the pre-commit runs on a file by file basis rather than a whole project,
    # The excludes in pyproject.toml are ignored
    exclude: migrations
    language_version: python3
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.0.1
  hooks:
  - id: reorder-python-imports
    language_version: python3
